### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by pulkitsinghal**
use remote box as the primary location for running all/most of the git commands

only use local box for code edits

### CODE REVIEW

**Comment by kamal0808** [comment]
@yogesh8177 Please review this

**Comment by pulkitsinghal** [comment]
Team, you gots to keep up on the docs, can't fall behind!

cc @yogesh8177 @kamal0808

**Comment by kamal0808** [comment]
I will find time to review this, on my to-do list

**Comment by pulkitsinghal** [comment]
Closing this PR because no one is reviewing it properly. Will open a new one with more updated to grab your attention.

**Comment by kamal0808** [comment]
Sorry man, got my hands full. So much to be done. Should wait until the first production release of bin locations at least. I can't do it till then

**Comment by kamal0808** [comment]
I appreciate the help in keeping things up to date btw, means a lot

**Pull request closed without merging**
