### PR TITLE
updated the script for comments & removed sqs questions

### PR DESCRIPTION
**Pull request by Bhushan001**

### CODE REVIEW

**Comment by pulkitsinghal** [comment]
@Bhushan001 - my PR was not merged so I had to:
1. merge my PR to develop
2. then checkout your branch
3. run `git rebase develop`
4. force push the merge conflict resolution to github
5. now i'm working on the doc changes that you intended to make
6. next i'll actually run and test drive the CLI wizard

**Comment by Bhushan001** [comment]
@pulkitsinghal sounds good. let me knoe your feedback. will resolce those

**Comment by pulkitsinghal** [comment]
done with step5, now working on step6

**Comment by pulkitsinghal** [comment]
@Bhushan001 - in the meantime, find a way to *force* `git pull` this branch again `feature/bhushan/cli-tool` otherwise you will have trouble adding stuff to it

**Comment by pulkitsinghal** [comment]
maybe this:
```
git fetch --all
git reset --hard feature/bhushan/cli-tool
git pull origin feature/bhushan/cli-tool
```

**Comment by pulkitsinghal** [comment]
You can merge this one but the order in which things are being asked and what is being asked is not ideal. You can merge this PR but we should talk and spec out the requirements before you do another PR.

**Comment by Bhushan001** [comment]
@pulkitsinghal sure. I will be merging this one after doing few changes.

**Pull request merged**
