### PR TITLE
Yogesh/feature/terraform setup

### PR DESCRIPTION
**Pull request by yogesh8177**
Terraform setup that provisions queues and sets up env variable files with the SQS URL and REGION returned by queues. This is for local setup which doesn't require azure instance, rather it expects local machine.

### CODE REVIEW

**Comment by pulkitsinghal** [comment]
@yogesh8177 - you may have unintentionally checked in the `warehouse-workers` submodule hash ... please remove it from the PR if it has nothing to do with what you want to commit.

**Comment by pulkitsinghal** [comment]
Here's what I did:

1. git clone --recursive git@github.com:ShoppinPal/warehouse.git warehouse-pr-252
2. cd warehouse-pr-252
3. git fetch origin
4. git checkout -b yogesh/feature/terraform-setup origin/yogesh/feature/terraform-setup
5. then i used sourcetree to drill down into `warehouse-workers` submodule visually and switched it from `HEAD` to the `develop` branch then closed sourcetree
6. came back to `cd warehouse-pr-252` in my CLI and ran `git rebase develop`

@yogesh8177 - At this point I ran into conflicts which I think you should resolve and then send a `git push -f` version of your feature branch after making sure that everything is up to date.

**Comment by pulkitsinghal** [comment]
@yogesh8177 - update `$PROJECT_ROOT/terraform/README.md` so there aren't any duplicate instructions compared to `$PROJECT_ROOT/README.md` then go ahead and merge this

**Comment by kamal0808** [comment]
@yogesh8177 This can be merged. Please go ahead, rebase and merge this.

**Pull request merged**
